version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    # - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    # - depguard
    - dogsled
    # - dupl
    - dupword
    - durationcheck
    # - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - exhaustruct
    - fatcontext
    - forbidigo
    - forcetypeassert
    # - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # - godot
    # - godox
    # - gofumpt
    - goheader
    # - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    # - ireturn
    # - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    # - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    # - nlreturn
    # - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    # - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    # - stylecheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # - varnamelen
    - wastedassign
    - whitespace
    # - wrapcheck
    # - wsl
    - zerologlint
  settings:
    revive:
      severity: error
      enable-all-rules: true
      rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#add-constant
        - name: add-constant
          disabled: true
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#get-return
        - name: get-return
          disabled: true
        - name: function-length
          exclude:
            - '**/*_test.go'
        - name: flag-parameter
          disabled: true
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#import-alias-naming
        - name: import-alias-naming
          disabled: true
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#line-length-limit
        - name: line-length-limit
          arguments:
            - 120
          disabled: true
          exclude:
            - ""
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#max-public-structs
        - name: max-public-structs
          disabled: true
        - name: unchecked-type-assertion
          arguments:
            - acceptIgnoredAssertionResult: true
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          exclude:
            - ""
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-naming
        - name: var-naming
          disabled: true
    tagliatelle:
      case:
        rules:
          json: snake
        use-field-name: true
        ignored-fields:
          - TemplateId
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - prisma
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - prisma
      - third_party$
      - builtin$
      - examples$
