FROM golang:1.24

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go install github.com/steebchen/prisma-client-go@latest

CMD ["go", "run", "github.com/steebchen/prisma-client-go", "migrate", "deploy"]
