FROM golang:1.24-alpine

WORKDIR /app

COPY go.mod .
COPY go.sum .
COPY prisma/ .

RUN go install github.com/steebchen/prisma-client-go@latest

CMD ["go", "run", "github.com/steebchen/prisma-client-go", "migrate", "deploy"]
