name: keyz
services:
  showcase:
    container_name: keyz-showcase
    build:
      context: ./ShowcaseKeyz/
      args:
        - VITE_API_URL=${VITE_API_URL}
    # image: mazettt/keyz-showcase:latest
    restart: always
    ports:
      - 3003:3003
    depends_on:
      server:
        condition: service_healthy
  frontend:
    container_name: keyz-frontend
    build:
      context: ./Web/
      args:
        - VITE_API_URL=${VITE_API_URL}
    # image: mazettt/keyz-frontend:latest
    restart: always
    ports:
      - 3002:3002
    depends_on:
      server:
        condition: service_healthy
  server:
    container_name: keyz-server
    build: ./Server/
    # image: mazettt/keyz-server:latest
    restart: always
    ports:
      - 3001:3001
    env_file: ./Server/.env.docker
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
  migrate:
    container_name: keyz-migrate
    build:
      context: ./Server/
      dockerfile: Dockerfile.migrate
    # image: mazettt/keyz-migrate:latest
    restart: "no"
    env_file: ./Server/.env.docker
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: keyz-db
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keyz
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: ./Server/password.txt
