name: android-unit-tests

on:
  workflow_call:
  push:
    branches:
      - android-dev
    paths:
      - 'Code/Mobile_Android/**'
      - '.github/workflows/build-android.yml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'Code/Mobile_Android/**'
  

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run unit tests
      run:  cd Code/Mobile_Android && ./gradlew test