name: Build Backend

on:
  push:
    branches:
      - backend
      - backendActions
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Code/Server/

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Build
        run: ./build.sh

      - name: Install linter
        run: sudo snap install golangci-lint --classic

      - name: Run linter
        run: ./run_linter.sh

      - name: Test
        id: test
        run: |
          OUTPUT=$(./run_tests.sh no-interactive)
          echo "# Coverage report" >> $GITHUB_STEP_SUMMARY
          echo $OUTPUT >> $GITHUB_STEP_SUMMARY
          echo "COVERAGE=$(echo $OUTPUT | grep total | grep -o '[0-9]\+\(\.[0-9]\+\)\?' | cut -d. -f1)" >> "$GITHUB_OUTPUT"

      - name: Check coverage requirements
        run: |
          COVERAGE=${{ steps.test.outputs.COVERAGE }}
          if [ "$COVERAGE" -lt 75 ]; then
            echo "The unit test coverage must me greater than 75%"
            exit 1
          fi
