name: build-server

on:
  workflow_call:
  push:
    branches:
      - backend
  pull_request:
    branches:
      - main

jobs:
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Code/Server/

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Build
        run: make build

      - name: Install linter
        run: sudo snap install golangci-lint --classic

      - name: Run linter
        run: make lint

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Test
        id: test
        run: |
          OUTPUT=$(make test)
          echo "# Test and coverage report" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`txt" >> $GITHUB_STEP_SUMMARY
          echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "COVERAGE=$(echo "$OUTPUT" | grep "Coverage: " | grep -o '[0-9]\+\(\.[0-9]\+\)\?' | cut -d. -f1)" >> "$GITHUB_OUTPUT"
          echo "$OUTPUT"

      - name: Check coverage requirements
        run: |
          COVERAGE=${{ steps.test.outputs.COVERAGE }}
          if [ "$COVERAGE" -lt 80 ]; then
            echo "The unit test coverage must me greater than 80% but got $COVERAGE%"
            exit 1
          fi
