name: deploy-prod

on:
  push:
    branches:
      - main

jobs:
  check-build-web:
    uses: ./.github/workflows/build-web.yml

  check-build-server:
    uses: ./.github/workflows/build-server.yml

  check-build-android:
    uses: ./.github/workflows/build-android.yml

  deploy-prod:
    needs: [check-build-server, check-build-web]
    runs-on: ubuntu-latest
    environment: prod
    concurrency: deploy_prod

    steps:
      - uses: actions/checkout@v4

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          script: |
            cd /home/${{ vars.DEPLOY_USER }}/Immotep/Code/
            git switch main
            docker compose down
            git pull
            docker compose up --build -d

  create-tag:
    needs: deploy-prod
    uses: ./.github/workflows/create-version-tag.yml

  create-release:
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.create-tag.outputs.version }}
        run: gh release create ${{ needs.create-tag.outputs.version }} --verify-tag --fail-on-no-commits --title ${{ needs.create-tag.outputs.version }} --generate-notes --repo="$GITHUB_REPOSITORY"
