name: deploy-dev

on:
  push:
    branches:
      - deploy/dev

jobs:
  check-build-web:
    uses: ./.github/workflows/build-web.yml

  check-build-server:
    uses: ./.github/workflows/build-server.yml

  check-build-android:
    uses: ./.github/workflows/build-android.yml

  deploy-dev:
    needs: [check-build-server, check-build-web]
    runs-on: ubuntu-latest
    environment: dev
    concurrency: deploy_dev

    steps:
      - uses: actions/checkout@v4

      # This step checks if there are any tables in the database with 0 rows. This is to be sure that the new migrations can be applied without issues.
      - name: Check any database tables with 0 rows
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          script: |
            docker exec -it immotep-db bash -c "! echo 'SELECT relname, n_live_tup FROM pg_stat_user_tables;' | psql immotep | grep ' 0'"

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          script: |
            cd /home/${{ vars.DEPLOY_USER }}/Immotep/Code/
            git switch dev
            docker compose down
            git pull
            docker compose up --build -d
