name: deploy

on:
  workflow_call:
    inputs:
      deploy_env:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}
    concurrency: deploy_${{ inputs.deploy_env }}

    steps:
      - uses: actions/checkout@v4

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: cd /home/${{ vars.DEPLOY_USER }}/Immotep/Code/ && git switch main && git pull && docker compose down && docker compose up --build -d
