name: deploy

on:
  workflow_call:
    inputs:
      username:
        type: string
        required: true
      host:
        type: string
        required: true
      key:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ inputs.host }}
          username: ${{ inputs.username }}
          key: ${{ inputs.key }}
          script: cd /home/${{ inputs.username }}/Immotep/Code/ && git switch main && git pull && docker compose down && docker compose up --build -d
