name: deploy-dev

on:
  push:
    branches:
      - dev
      - build
  pull_request:
    branches:
      - main

jobs:
  check-build:
    uses: ./.github/workflows/check-build.yml

  deploy-dev:
    needs: [check-build]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: dev
    concurrency: deploy_dev

    steps:
      - uses: actions/checkout@v4

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          script: |
            cd /home/${{ vars.DEPLOY_USER }}/Immotep/Code/
            git switch dev
            docker compose down
            git pull
            docker compose up --build -d
