name: deploy-dev

on:
  push:
    branches:
      - dev
      - build
  pull_request:
    branches:
      - main

jobs:
  check-build:
    uses: ./.github/workflows/check-build.yml

  deploy-dev:
    needs: [check-build]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: dev
    concurrency: deploy_dev
    steps:
      - uses: ./.github/workflows/deploy.yml
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
