name: deploy-dev

on:
  push:
    branches:
      - dev
      - build
  pull_request:
    branches:
      - main

jobs:
  check-build:
    uses: ./.github/workflows/check-build.yml

  deploy-dev:
    needs: [check-build]
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_env: dev
