name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    if: github.repositoryUrl == 'git://github.com/Immotep-EIP/Immotep.git'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/G-EIP-700-MLH-7-1-eip-lucas.binder.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
