name: Android CI 🤖

on:
  push:
    branches:
      - main
      - android-dev
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [30]
        target: [default]
        arch: [x86_64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Change directory to Mobile_Android
        working-directory: Code/Mobile_Android
        run: echo "Changed working directory to Code/Mobile_Android"

      - name: Run unit tests
        working-directory: Code/Mobile_Android
        run: ./gradlew test

      - name: Start emulator
        run: |
          adb devices
          $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -no-snapshot -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          adb shell getprop sys.boot_completed | grep -m 1 '1'

      - name: Run instrumented tests
        working-directory: Code/Mobile_Android
        run: ./gradlew connectedAndroidTest

      - name: Kill emulator
        run: adb emu kill
