name: deploy-prod

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*'

jobs:
  check-build:
    uses: ./.github/workflows/check-build.yml

  deploy-prod:
    needs: [check-build]
    runs-on: ubuntu-latest
    environment: prod
    concurrency: deploy_prod

    steps:
      - uses: actions/checkout@v4

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          script: |
            cd /home/${{ vars.DEPLOY_USER }}/Immotep/Code/
            git switch main
            docker compose down
            git pull
            docker compose up --build -d
