name: deploy-prod

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*'

jobs:
  check-build:
    uses: ./.github/workflows/check-build.yml

  deploy-prod:
    needs: [check-build]
    runs-on: ubuntu-latest
    environment: prod
    concurrency: deploy_prod
    steps:
      - uses: ./.github/workflows/deploy.yml
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
