name: deploy-prod

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*'

jobs:
  check-build:
    uses: ./.github/workflows/check-build.yml

  deploy-prod:
    needs: [check-build]
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_env: prod
